spring:
  application:
    name: cloud-server

server:
  host: http://localhost
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true